name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Gemini Key
        run: |
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          # Add this to bypass Docker issues:
          skipDependencies: true